/*
   This file is part of LilyPond, the GNU music typesetter.

   Copyright (C) 2016--2026 John Gourlay <john@weathervanefarm.net>
   Copyright (C) 2024--2026 Werner Lemberg <wl@gnu.org>

   LilyPond is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   LilyPond is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with LilyPond.  If not, see <http://www.gnu.org/licenses/>.
*/

using System;
using System.Collections.Generic;

namespace CodeBrix.LilyPort.Importers; //was previously: python/musicxml2ly_definitions.py;

// Modified by Jeremy Ellis - 2026 - as part of the CodeBrix.LilyPort port.

/// <summary>The LilyPond definitions a converted score may need.</summary>
/// <remarks>
/// These are upstream's own snippets, copied verbatim. They are the licensed work rather
/// than program output (rule 17, case (b)), and GPL-3.0-or-later into a GPL-3.0-only
/// package is clean.
/// </remarks>
internal static class MusicXmlDefinitions
{
    private static readonly Dictionary<string, string> AdditionalDefinitions
        = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            {
                "accidental-marks",
                "% \\accs-ornament\n"
                + "% --------------\n"
                + "%\n"
                + "% Position the `above` and `below` markup lists as vertical stacks\n"
                + "% above and below markup `script`, respectively.  `above` and `below`\n"
                + "% are by default horizontally centered on `script` (controlled by the\n"
                + "% property `acc-dir`), printed at a size given by the property\n"
                + "% `acc-font-size` (default value -5), and a color given by the\n"
                + "% property `acc-color` (default is black).  Between all markups a\n"
                + "% vertical space given by the property `acc-padding` (default value\n"
                + "% 0.2) is inserted.  The `above` stack grows from bottom to top, while\n"
                + "% the `below` stack grows from top to bottom.\n"
                + "%\n"
                + "% If either `above` or `below` is an empty argument, or if `script` is\n"
                + "% set to `#f`, the corresponding argument is not printed.\n"
                + "%\n"
                + "% If an element of `above`, `script`, or `below` is a plain string,\n"
                + "% check the following.\n"
                + "%\n"
                + "% * If the string consists entirely of one or more characters from the\n"
                + "%   accidental set '♮♭♯𝄪𝄫' (not counting a possible enclosure), add\n"
                + "%   `\\number` internally as a prefix to use the Emmentaler font.\n"
                + "%\n"
                + "% * Otherwise the element is taken as a glyph name (again not counting\n"
                + "%   a possible enclosure), to be internally accessed with the\n"
                + "%   `\\musicglyph` command.\n"
                + "%\n"
                + "% * (Not for `script`.)  If an element of `above` or `below` is a\n"
                + "%   plain string and the first and last character is `(` and `)`,\n"
                + "%   respectively, the element gets enclosed in parentheses.  The same\n"
                + "%   holds for `[` and `]`, enclosing the element in brackets.  The\n"
                + "%   font size of the enclosure characters is controlled by the\n"
                + "%   property `enclosure-font-size` (default value -2).\n"
                + "%\n"
                + "% Example:\n"
                + "%\n"
                + "% ```\n"
                + "% \\markup \\override #'(acc-padding . 0.5)\n"
                + "%         \\accs-ornament { \"♭\" \"(♯)\" } \"scripts.haydnturn\" {}\n"
                + "% ```\n"
                + "\n"
                + "#(define-markup-command (accs-ornament layout props\n"
                + "                                       above script below)\n"
                + "   (markup-list? markup? markup-list?)\n"
                + "   #:properties ((acc-font-size -5)\n"
                + "                 (acc-color black)\n"
                + "                 (acc-padding 0.3)\n"
                + "                 (acc-dir CENTER)\n"
                + "	         (enclosure-font-size -2))\n"
                + "\n"
                + "   (define enclosure-regex\n"
                + "     ;; `(?(-3) ...)` is a 'conditional subpattern' that is only\n"
                + "     ;; considered for matching if the subpattern three opening\n"
                + "     ;; parentheses earlier (i.e., the first group) matches.\n"
                + "     (ly:make-regex \"(?x) ^ ( [([] ) ?\n"
                + "                            ( [^]()[] + )\n"
                + "                            ( (?(-3) [])] ) ) $\"))\n"
                + "\n"
                + "   (define charset:accidentals (string->char-set \"♮♭♯𝄪𝄫\"))\n"
                + "\n"
                + "   (define (musicglyph-or-number-markup arg)\n"
                + "     (if (string-every charset:accidentals arg)\n"
                + "         (make-number-markup arg)\n"
                + "         (make-musicglyph-markup arg)))\n"
                + "\n"
                + "   (define (with-enclosure-markup arg)\n"
                + "     (let ((match (ly:regex-exec enclosure-regex arg)))\n"
                + "       (if match\n"
                + "           (let* (;; `left` is `#f` if there is no enclosure.\n"
                + "                  (left (ly:regex-match-substring match 1))\n"
                + "                  (left (if left\n"
                + "                            (make-normalsize-markup\n"
                + "                             (make-fontsize-markup\n"
                + "                              enclosure-font-size left))\n"
                + "                            #f))\n"
                + "                  (glyph (ly:regex-match-substring match 2))\n"
                + "                  ;; `right` is `\"\"` if there is no enclosure.\n"
                + "                  (right (ly:regex-match-substring match 3))\n"
                + "                  (right (if (string-null? right)\n"
                + "                             #f\n"
                + "                             (make-normalsize-markup\n"
                + "                              (make-fontsize-markup\n"
                + "                               enclosure-font-size right)))))\n"
                + "             (make-concat-markup\n"
                + "              (list\n"
                + "               (or left \"\")\n"
                + "               (musicglyph-or-number-markup glyph)\n"
                + "               (or right \"\"))))\n"
                + "           #f)))\n"
                + "\n"
                + "   (define (to-markup arg enclosure)\n"
                + "     (if (string? arg)\n"
                + "	 (if (string-null? arg)\n"
                + "             #f\n"
                + "             (if enclosure\n"
                + "                 (with-enclosure-markup arg)\n"
                + "                 (musicglyph-or-number-markup arg)))\n"
                + "         arg))\n"
                + "\n"
                + "   (define (make-acc-stencil arg)\n"
                + "     (if arg\n"
                + "         (interpret-markup\n"
                + "          layout props\n"
                + "          (make-halign-markup\n"
                + "           acc-dir\n"
                + "           (make-with-color-markup\n"
                + "            acc-color\n"
                + "            (make-fontsize-markup\n"
                + "             acc-font-size arg))))\n"
                + "         #f))\n"
                + "\n"
                + "   (let* ((above (map (lambda (x) (to-markup x #t)) above))\n"
                + "          (above-stils (map (lambda (x)\n"
                + "                              (make-acc-stencil x))\n"
                + "                            above))\n"
                + "\n"
                + "          (script (to-markup script #f))\n"
                + "          (script-stil (if script\n"
                + "                           (interpret-markup layout props script)\n"
                + "                           empty-stencil))\n"
                + "\n"
                + "          (below (map (lambda (x) (to-markup x #t)) below))\n"
                + "          (below-stils (map (lambda (x)\n"
                + "                              (make-acc-stencil x))\n"
                + "                            below))\n"
                + "\n"
                + "          (script-stil (fold (lambda (elem previous)\n"
                + "                               (ly:stencil-combine-at-edge\n"
                + "                                previous Y UP elem acc-padding))\n"
                + "                             script-stil\n"
                + "                             above-stils))\n"
                + "          (script-stil (fold (lambda (elem previous)\n"
                + "                               (ly:stencil-combine-at-edge\n"
                + "                                previous Y DOWN elem acc-padding))\n"
                + "                             script-stil\n"
                + "                             below-stils)))\n"
                + "     script-stil))\n"
                + "\n"
                + "\n"
                + "% \\acc-ornament\n"
                + "% -------------\n"
                + "%\n"
                + "% This function behaves similar to `\\accs-ornament` with the\n"
                + "% difference that `above` and `below` are single markups, not markup\n"
                + "% lists.  If one of the arguments is an empty string, it is not\n"
                + "% printed.\n"
                + "%\n"
                + "% Example:\n"
                + "%\n"
                + "% ```\n"
                + "% \\markup \\acc-ornament \"[♭]\" \"scripts.turn\" ♯\n"
                + "% ```\n"
                + "\n"
                + "#(define-markup-command (acc-ornament layout props\n"
                + "                                      above script below)\n"
                + "   (markup? markup? markup?)\n"
                + "   #:properties (accs-ornament-markup)\n"
                + "   (accs-ornament-markup layout props\n"
                + "                         (if (and (string? above) (string-null? above))\n"
                + "                             '()\n"
                + "                             (list above))\n"
                + "                         (if (and (string? script) (string-null? script))\n"
                + "                             #f\n"
                + "                             script)\n"
                + "                         (if (and (string? below) (string-null? below))\n"
                + "                             '()\n"
                + "                             (list below))))\n"
                + "\n"
                + "\n"
                + "% Some shorthands to make the usage of `\\acc-ornament` more\n"
                + "% comfortable for simple cases.\n"
                + "\n"
                + "\n"
                + "ornament =\n"
                + "#(define-music-function (above script below)\n"
                + "   (string? string? string?)\n"
                + "   #{\n"
                + "     \\tweak parent-alignment-X #CENTER\n"
                + "     \\tweak self-alignment-X #CENTER\n"
                + "     -\\markup \\acc-ornament #above #script #below\n"
                + "   #})\n"
                + "\n"
                + "\n"
                + "accTrill =\n"
                + "#(define-music-function (above)\n"
                + "   (string?)\n"
                + "   #{\n"
                + "     \\tweak parent-alignment-X #CENTER\n"
                + "     \\tweak self-alignment-X #CENTER\n"
                + "     -\\markup\n"
                + "        \\override #'((acc-dir . -1.3)\n"
                + "                     (acc-padding . -0.4))\n"
                + "        \\acc-ornament #above \"scripts.trill\" \"\"\n"
                + "   #})\n"
                + "\n"
                + "\n"
                + "#(define-markup-command (trill-acc-tweak layout props above)\n"
                + "   (string?)\n"
                + "   (interpret-markup\n"
                + "    layout props\n"
                + "    #{\n"
                + "      \\markup\n"
                + "        \\override #'((acc-dir . -1.3)\n"
                + "                     (acc-padding . -0.4))\n"
                + "        \\with-dimension-from #X\n"
                + "          \\with-true-dimension #X \\musicglyph \"scripts.trill\"\n"
                + "            \\acc-ornament\n"
                + "              #above\n"
                + "              \\with-true-dimension #X \\musicglyph \"scripts.trill\"\n"
                + "          \"\"\n"
                + "    #}))\n"
                + "\n"
                + "\n"
                + "% `color` and `size` are optional.  If `size` is present, `color` must\n"
                + "% be present, too.  `size` also sets the `enclosure-font-size`\n"
                + "% property (three magsteps larger).\n"
                + "trillTweak =\n"
                + "#(define-music-function (acc color size music)\n"
                + "   (string? (color? black) (number?) ly:music?)\n"
                + "   (let* ((override (list `(acc-color . ,color)))\n"
                + "          (override (if size\n"
                + "                        (cons `(enclosure-font-size . ,(+ size 3))\n"
                + "                         (cons `(acc-font-size . ,size) override))\n"
                + "                        override)))\n"
                + "     #{\n"
                + "       \\tweak bound-details.left.text\n"
                + "         \\markup \\override #override\n"
                + "                   \\trill-acc-tweak #acc\n"
                + "       #music\n"
                + "     #}))\n"
            },
            {
                "arpeggioXX",
                "% For cross-staff arpeggios.\n"
                + "arpeggioXX =\n"
                + "  \\once \\set PianoStaff.connectArpeggios = ##t\n"
                + "arpeggioArrowUpXX =\n"
                + "  \\once \\override PianoStaff.Arpeggio.arpeggio-direction = #UP\n"
                + "arpeggioArrowDownXX =\n"
                + "  \\once \\override PianoStaff.Arpeggio.arpeggio-direction = #DOWN\n"
                + "arpeggioBracketXX =\n"
                + "  \\once \\override PianoStaff.Arpeggio.stencil =\n"
                + "    #ly:chord-bracket::print\n"
            },
            {
                "arpeggioX",
                "% For cross-voice arpeggios.\n"
                + "arpeggioX =\n"
                + "  \\once \\set Staff.connectArpeggios = ##t\n"
                + "arpeggioArrowUpX =\n"
                + "  \\once \\override Staff.Arpeggio.arpeggio-direction = #UP\n"
                + "arpeggioArrowDownX =\n"
                + "  \\once \\override Staff.Arpeggio.arpeggio-direction = #DOWN\n"
                + "arpeggioBracketX =\n"
                + "  \\once \\override Staff.Arpeggio.stencil =\n"
                + "    #ly:chord-bracket::print\n"
            },
            {
                "cancel-after-key",
                "cancelAfterKey = {\n"
                + "  \\once \\set Staff.printKeyCancellation = ##t\n"
                + "  \\once \\override Score.BreakAlignment.break-align-orders =\n"
                + "  #(grob-transformer\n"
                + "    'break-align-orders\n"
                + "    (lambda (grob orig)\n"
                + "      (let* ((middle (vector-ref orig 1))\n"
                + "             (middle (delq 'key-signature middle))\n"
                + "             (middle (insert-before 'key-cancellation 'key-signature middle)))\n"
                + "        (vector\n"
                + "         (vector-ref orig 0)\n"
                + "         middle\n"
                + "         (vector-ref orig 2)))))\n"
                + "}\n"
            },
            {
                "cancel-before-barline",
                "cancelBeforeBarline = {\n"
                + "  \\once \\set Staff.printKeyCancellation = ##t\n"
                + "  \\once \\override Score.BreakAlignment.break-align-orders =\n"
                + "  #(grob-transformer\n"
                + "    'break-align-orders\n"
                + "    (lambda (grob orig)\n"
                + "      (let* ((middle (vector-ref orig 1))\n"
                + "             (middle (delq 'key-cancellation middle))\n"
                + "             (middle (insert-before 'staff-bar 'key-cancellation middle)))\n"
                + "        (vector\n"
                + "         (vector-ref orig 0)\n"
                + "         middle\n"
                + "         (vector-ref orig 2)))))\n"
                + "}\n"
            },
            {
                "crescendo",
                "Cresc = #(make-music 'CrescendoEvent 'span-direction START\n"
                + "                                     'span-type 'text)\n"
            },
            {
                "decrescendo",
                "Decresc = #(make-music 'DecrescendoEvent 'span-direction START\n"
                + "                                         'span-type 'text)\n"
            },
            {
                "fingering-substitution",
                "substFinger =\n"
                + "#(define-music-function (start left right)\n"
                + "   (markup? markup? markup?)\n"
                + "   #{\n"
                + "     \\tweak self-alignment-X #-0.6\n"
                + "     -\\finger \\markup\n"
                + "       \\concat {\n"
                + "         #start\n"
                + "         \\overtie \\concat { #left \\char ##x2009 #right } }\n"
                + "   #})\n"
            },
            {
                "for-barline",
                "% This `\\caesura` creates a light-light bar line where there isn't\n"
                + "% already a more significant bar line, and aligns its decorations\n"
                + "% (e.g., fermatas) to the bar line.\n"
                + "forBarLine =\n"
                + "{\n"
                + "  \\once \\set Staff.caesuraType = #'((underlying-bar-line . \"||\"))\n"
                + "  \\once \\set Staff.caesuraTypeTransform = ##f\n"
                + "  \\caesura\n"
                + "}\n"
            },
            {
                "harmonic",
                "harmonicSmall =\n"
                + "  \\tweak NoteHead.font-size #-3\n"
                + "  \\tweak NoteHead.duration-log #4\n"
                + "  \\etc\n"
                + "\n"
                + "harmonicParen =\n"
                + "#(define-music-function (size offset music)\n"
                + "   (number? number? ly:music?)\n"
                + "   #{\n"
                + "     \\tweak Parentheses.font-size #size\n"
                + "     \\tweak Parentheses.Y-offset #offset\n"
                + "     \\parenthesize\n"
                + "     #music\n"
                + "   #})\n"
            },
            {
                "hide-note",
                "hideNote =\n"
                + "  \\tweak Dots.transparent ##t\n"
                + "  \\tweak NoteHead.transparent ##t\n"
                + "  \\tweak NoteHead.no-ledgers ##t\n"
                + "  \\tweak Stem.transparent ##t\n"
                + "  \\tweak Accidental.transparent ##t\n"
                + "  \\tweak Rest.transparent ##t\n"
                + "  \\tweak TabNoteHead.transparent ##t \\etc\n"
            },
            {
                "insert-before",
                "#(define (insert-before where what lst)\n"
                + "   (cond ((null? lst)\n"
                + "          (list what))\n"
                + "         ((eq? where (car lst))\n"
                + "          (cons what lst))\n"
                + "         (else\n"
                + "          (cons (car lst) (insert-before where what (cdr lst))))))\n"
            },
            {
                "make-bracketed",
                "#(define make-bracketed\n"
                + "   (grob-transformer\n"
                + "    'stencil\n"
                + "    (lambda (grob orig)\n"
                + "      (let* ((paren-stil (grob-interpret-markup\n"
                + "                          grob\n"
                + "                          (markup #:musicglyph \"accidentals.leftparen\")))\n"
                + "             (ext (ly:stencil-extent paren-stil Y))\n"
                + "             (stil (ly:accidental-interface::print grob))\n"
                + "             (thick (ly:output-def-lookup (ly:grob-layout grob)\n"
                + "                                          'line-thickness 0.1))\n"
                + "             (padding thick)\n"
                + "             (protrusion (* 2.5 thick))\n"
                + "             (lb (ly:bracket Y ext thick protrusion))\n"
                + "             (rb (ly:bracket Y ext thick (- protrusion))))\n"
                + "        (set! stil (ly:stencil-combine-at-edge stil X 1 rb padding))\n"
                + "        (set! stil (ly:stencil-combine-at-edge stil X -1 lb padding))\n"
                + "        stil))))\n"
                + "\n"
                + "bracketAcc =\n"
                + "  \\tweak AccidentalCautionary.parenthesized ##f\n"
                + "  \\tweak AccidentalCautionary.stencil #make-bracketed \\etc\n"
            },
            {
                "make-edge-height",
                "#(define edge-height-alist\n"
                + "   '((up . -0.7)\n"
                + "     (down . 0.7)\n"
                + "     (none . 0)))\n"
                + "\n"
                + "#(define (get-height type)\n"
                + "   (or (assv-ref edge-height-alist type)\n"
                + "       (begin\n"
                + "         (ly:warning \"bracket edge type '~a' not implemented\" type)\n"
                + "         0)))\n"
                + "\n"
                + "% Make the `edge-height` property independent of a bracket's direction.\n"
                + "#(define (make-edge-height left right)\n"
                + "   (grob-transformer\n"
                + "    'edge-height\n"
                + "    (lambda (grob orig)\n"
                + "      (let ((dir (ly:grob-property grob 'direction))\n"
                + "            (left-height (get-height left))\n"
                + "            (right-height (get-height right)))\n"
                + "        (cons (* dir left-height) (* dir right-height))))))\n"
            },
            {
                "measure-length",
                "measureLength =\n"
                + "#(define-music-function (length)\n"
                + "   (positive-musical-length-as-number?)\n"
                + "   #{\n"
                + "     \\pushContextProperty Timing.measureLength\n"
                + "     \\set Timing.measureLength = #length\n"
                + "   #})\n"
                + "measureLengthReset = \\popContextProperty Timing.measureLength\n"
            },
            {
                "pluck",
                "RH = \\rightHandFinger \\etc\n"
            },
            {
                "square",
                "#(define-markup-command (square layout props arg)\n"
                + "   (markup?)\n"
                + "   (let* ((stil (interpret-markup layout props arg))\n"
                + "          (x-size (interval-length (ly:stencil-extent stil X)))\n"
                + "          (y-size (interval-length (ly:stencil-extent stil Y)))\n"
                + "          (axis (if (> x-size y-size) Y X)))\n"
                + "     (interpret-markup\n"
                + "      layout props\n"
                + "      #{\n"
                + "        \\markup \\box \\with-dimension-from #axis \\rotate #90 #arg #arg\n"
                + "      #})))\n"
            },
            {
                "staff-lines",
                "% Change the number of staff lines to `num-lines`.\n"
                + "%\n"
                + "% The argument `clef` makes the function emit a clef with the given\n"
                + "% name.  If `clef` contains the substring `\"percussion\"` or `\"tab\"`,\n"
                + "% use both even and odd staff line positions.  If set to `\"\"`, do the\n"
                + "% same but don't set `Staff.clefPosition` (which means that no clef\n"
                + "% gets triggered).  If `clef` is set to any other value, use even\n"
                + "% staff line positions only and set `Staff.clefPosition`, which\n"
                + "% triggers a clef if its value changes.\n"
                + "%\n"
                + "% The optional argument `properties` is an alist of properties to\n"
                + "% control the appearance of both the staff and the clef:\n"
                + "%\n"
                + "% * `details` is a list of staff line numbers that should be\n"
                + "%   displayed.  An empty list suppresses any display of staff lines;\n"
                + "%   omitting the argument means to display all lines.\n"
                + "% * `staff-color` holds the color of the staff.\n"
                + "% * `clef-font-size` holds the font size of the clef\n"
                + "% * `clef-color` holds the color of the clef.\n"
                + "%\n"
                + "% \\staffLines [<properties>] <clef> <num-lines>\n"
                + "\n"
                + "staffLines =\n"
                + "#(define-music-function (properties clef num-lines)\n"
                + "                        ((alist? '()) string? index?)\n"
                + "   (let* ((details (assoc-get 'details properties #f))\n"
                + "          (staff-color (assoc-get 'staff-color properties #f))\n"
                + "          (clef-color (assoc-get 'clef-color properties #f))\n"
                + "          (clef-font-size (assoc-get 'clef-font-size properties #f))\n"
                + "          (lines (or details (iota num-lines 1)))\n"
                + "          (only-even-pos (not (or (equal? clef \"\")\n"
                + "                                  (string-contains clef \"percussion\")\n"
                + "                                  (string-contains clef \"tab\"))))\n"
                + "          (offset (if only-even-pos\n"
                + "                      (if (even? num-lines) 1 0)\n"
                + "                      0))\n"
                + "          ;; MusicXML counts staff lines from the bottom.\n"
                + "          (delta (- -1 num-lines offset))\n"
                + "          (positions (filter (lambda (x) (<= x num-lines))\n"
                + "                             lines))\n"
                + "          (positions (map (lambda (x) (+ delta (* x 2)))\n"
                + "                      positions)))\n"
                + "     #{\n"
                + "       \\stopStaff\n"
                + "\n"
                + "       #(if staff-color\n"
                + "            #{\n"
                + "              \\once \\override Staff.StaffSymbol.color = #staff-color\n"
                + "            #})\n"
                + "       #(if clef-color\n"
                + "            #{\n"
                + "              \\once \\override Staff.Clef.color = #clef-color\n"
                + "            #})\n"
                + "       #(if clef-font-size\n"
                + "            #{\n"
                + "              \\once \\override Staff.Clef.font-size = #clef-font-size\n"
                + "            #})\n"
                + "\n"
                + "       #(if (equal? clef \"\")\n"
                + "            #{\n"
                + "              \\unset Staff.middleCPosition\n"
                + "              \\unset Staff.middleCClefPosition\n"
                + "              % To suppress the clef inserted by default by LilyPond at the\n"
                + "              % beginning of a piece.\n"
                + "              \\once \\omit Staff.Clef\n"
                + "            #}\n"
                + "            #{ \\clef #clef #})\n"
                + "\n"
                + "       \\override Staff.StaffSymbol.line-positions = #positions\n"
                + "\n"
                + "       \\applyContext\n"
                + "       #(lambda (ctx)\n"
                + "          (let* ((c (ly:context-find ctx 'Staff))\n"
                + "                 (clef-p (ly:context-property c 'clefPosition))\n"
                + "                 (middle-c-p (ly:context-property c 'middleCPosition))\n"
                + "                 (middle-c-clef-p (ly:context-property c 'middleCClefPosition))\n"
                + "                 (use-offset (not (string-contains clef \"percussion\")))\n"
                + "                 (delta (+ delta (if use-offset 6 0))))\n"
                + "            (when only-even-pos\n"
                + "              (ly:context-set-property! c 'clefPosition (+ clef-p delta))\n"
                + "              (ly:context-set-property! c 'forceClef #t))\n"
                + "            (ly:context-set-property! c 'middleCPosition (+ middle-c-p delta))\n"
                + "            (ly:context-set-property! c 'middleCClefPosition\n"
                + "                                      (+ middle-c-clef-p delta))))\n"
                + "       \\startStaff\n"
                + "     #}))\n"
            },
            {
                "stem-directions",
                "D = \\tweak Stem.direction #DOWN \\etc\n"
                + "U = \\tweak Stem.direction #UP \\etc\n"
            },
            {
                "time-alternate",
                "#(define ((time-alternate t ta type) grob)\n"
                + "   (let ((m1 (grob-interpret-markup grob (markup #:compound-meter t)))\n"
                + "         (m2 (grob-interpret-markup grob (markup #:compound-meter ta))))\n"
                + "     (ly:stencil-combine-at-edge\n"
                + "      m1 X RIGHT\n"
                + "      (case type\n"
                + "        ((bracket)\n"
                + "         (bracketify-stencil m2 Y 0.15 0.4 0 0.4))\n"
                + "        ((space)\n"
                + "         m2)\n"
                + "        ((equals)\n"
                + "         (ly:stencil-combine-at-edge\n"
                + "          (grob-interpret-markup grob (markup #:lower 1.0 #:number \"=\"))\n"
                + "          X RIGHT m2 0.1))\n"
                + "        ((hyphen)\n"
                + "         (ly:stencil-combine-at-edge\n"
                + "          (grob-interpret-markup grob (markup #:lower 0.55 #:number \"–\"))\n"
                + "          X RIGHT m2 0))\n"
                + "        ((slash)\n"
                + "         (ly:stencil-combine-at-edge\n"
                + "          (grob-interpret-markup grob (markup #:lower 1.0 #:number \"/\"))\n"
                + "          X RIGHT m2 0.2))\n"
                + "        (else\n"
                + "         (parenthesize-stencil m2 0.1 0.4 0.4 0.1)))\n"
                + "      (case type\n"
                + "        ((space) 0.7)\n"
                + "        ((equals) 0.1)\n"
                + "        ((hyphen) 0)\n"
                + "        ((slash) 0.2)\n"
                + "        (else 0.4)))))\n"
                + "\n"
                + "timeAlternate =\n"
                + "#(define-music-function (t ta type)\n"
                + "   (time-signature? time-signature? symbol?)\n"
                + "   #{\n"
                + "     \\once \\override Timing.TimeSignature.stencil = #(time-alternate t ta type)\n"
                + "     \\time #t\n"
                + "   #})\n"
            },
        };

    /// <summary>The definition one name asks for.</summary>
    /// <param name="name">The name.</param>
    /// <returns>The definition, or empty when the name is not one of upstream's.</returns>
    internal static string Get(string name)
        => name != null && AdditionalDefinitions.TryGetValue(name, out string value)
            ? value
            : string.Empty;

    /// <summary>Every definition name, so a caller can check the table's reach.</summary>
    internal static IEnumerable<string> Names => AdditionalDefinitions.Keys;
}
